### ISSUE TITLE
[soft delete] soft deleted items are updating again

### ISSUE THREAD

**Issue by raju-mechatronics** [ImtiazChowdhury/mongo-baseOps#2]
If we delete one item with soft delete enabled and do a delete on that item again it's showing delete count 1. But the product is already deleted.

**Comment by ImtiazChowdhury** [comment]
This is the predicted behaviour, as hard deleting soft deleted items is a purposeful action.

**Comment by ImtiazChowdhury** [comment]
This is the predicted behaviour, as hard deleting soft deleted items is a purposeful action.
